services:
  olympic-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    image: olympic-tracker:local
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - olympic-tracker-net

networks:
  olympic-tracker-net:
    name: olympic-tracker-net
