replicaCount: 1

image:
  repository: registry.gitlab.com/boncbonc-devops/proj4/devops_proj4_applicationangular
  tag: 2.1.0
  pullPolicy: Always
  pullSecretName: gitlab-registry-secret

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

resources: {}

nameOverride: ""
fullnameOverride: ""
